```{r}
url <- "http://labtrop.ib.usp.br/lib/exe/fetch.php?media=cursos:planeco:roteiro:praia.txt"

# Supondo que os dados estejam separados por espaços e que a primeira linha contenha os nomes das colunas
df <- read.table(url, header = TRUE, sep = "")
df

```

```{r}
df$fExposure <- ifelse(df$fExp == 10, "low", "high")
df$fExposure
```

```{r}

modelo.riqueza <- lmer(Richness ~ NAP +  (1 | Beach), data=df)
summary(modelo.riqueza)

```

```{r}
#criando objeto com os coeficientes do modelo (efeitos fixos)
fixLMM <- fixef(modelo.riqueza)
fixLMM
```

```{r}
#criando objeto com os coeficientes do modelo (efeitos fixos)
randLMM <- coef(modelo.riqueza)
randLMM

randLMM$Beach[,1] %>% mean()
randLMM$Beach[,2] %>% mean()
```
```{r}
seqNAP <- seq(-1.5, 2.5,len=100)
beach01 <- randLMM$Beach[1,1] + randLMM$Beach[1,2] * seqNAP
beach02 <- randLMM$Beach[2,1] + randLMM$Beach[2,2] * seqNAP
beach03 <- randLMM$Beach[3,1] + randLMM$Beach[3,2] * seqNAP
beach04 <- randLMM$Beach[4,1] + randLMM$Beach[4,2] * seqNAP
beach05 <- randLMM$Beach[5,1] + randLMM$Beach[5,2] * seqNAP
beach06 <- randLMM$Beach[6,1] + randLMM$Beach[6,2] * seqNAP
beach07 <- randLMM$Beach[7,1] + randLMM$Beach[7,2] * seqNAP
beach08 <- randLMM$Beach[8,1] + randLMM$Beach[8,2] * seqNAP
beach09 <- randLMM$Beach[9,1] + randLMM$Beach[9,2] * seqNAP
beachFix <- fixLMM[1] + fixLMM[2] * seqNAP
```

```{r}
cores <- rainbow(9)
par( mar=c(5,5,2,2))
plot(Richness ~ NAP ,data = df,
     pch = 19, col = cores[as.factor(Beach)] , las = 1,
     cex=1.5, cex.lab= 1.7, cex.axis = 1.5
     )

lines(beach01 ~ seqNAP, col = cores[1])
lines(beach02 ~ seqNAP, col = cores[2])
lines(beach03 ~ seqNAP, col = cores[3])
lines(beach04 ~ seqNAP, col = cores[4])
lines(beach05 ~ seqNAP, col = cores[5])
lines(beach06 ~ seqNAP, col = cores[6])
lines(beach07 ~ seqNAP, col = cores[7])
lines(beach08 ~ seqNAP, col = cores[8])
lines(beach09 ~ seqNAP, col = cores[9])
lines(beachFix ~ seqNAP, col = rgb(0,0,0,0.5), lwd=5)
legend("topright", c( "praia média",paste("praia", 1:9)) , lty=1, col= c(1,cores), bty="n", cex=1.5)

```

```{r}
library(lmerTest)
m0 <- lm(Richness ~ fExposure * NAP, data = df) #sem efeito aleat.
#m0 %>% summary()
m1 <- lmer(Richness ~ fExposure * NAP + (1|Beach), data = df)
#m1 %>% summary()
m2 <- lmer(Richness ~ fExposure * NAP + (NAP|Beach), data = df)
#m2 %>% summary()

anova(m1, m2, refit= FALSE)

anova(m1, m0, refit= FALSE)

```



```{r}

# modelo com interação entre Exposure e NAP
m1 <- lmer(Richness ~ fExposure + NAP + fExposure:NAP + (1|Beach), data=df, REML = F)

# modelo sem interação entre exposure e NAP
m3 <- lmer(Richness ~ fExposure + NAP + (1|Beach), data=df, REML = F)

anova(m1, m3, refit= FALSE)


```

```{r}
library(RVAideMemoire)

plotresid(m1, shapiro = T)
```


```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

