```{r Carregando base de dados}
source('https://raw.githubusercontent.com/GabrielGabes/Codigos-uteis/main/R%20program/executar_sempre.R')
df = dff
```

```{r Bibliotecas usadas}
library(tidyr) #manipulação de dados #pivot_longer
library(tibble)
library(broom)
```


```{r Analise Grafica Rapida}
# source('https://raw.githubusercontent.com/GabrielGabes/Codigos-uteis/main/R%20program/executar_sempre.R')
# 
# conti_grafi(df, 'desfecho', 'tratamentos')
# 
# box_vin_jit(df, 'var_num', 'desfecho')
# 
# box_vin_jit(df, 'var_num', 'tratamentos')
```


# Numerica vs Categórica

## Dois Grupos

### Parametrico

```{r Teste de Hipotese: Teste T; Post Hoc: D'Cohen}
t.test(df$idade~df$genero)
cohen.d(df$idade~df$genero)
```
```{r Teste de Homogenidade}
# Padrão
bartlett.test(df$idade ~ df$genero) # mais sensibilidade e potência em detectar diferenças de variâncias

# Levene
car::leveneTest(df$idade ~ df$genero) # não é tão sensivel a desvio de normalidade quanto bartlett, porém ainda tem o pressuposto

# Teste F de Fisher
var.test(df$idade ~ df$genero)
```

```{r Outros tipos de teste t}
# Aplicando o Welch t-test
t.test(df$idade ~ df$genero, var.equal = FALSE)

# Aplicando o Yuen-Welch t-test com 20% de aparagem - horrivel
pacman::p_load(WRS2)
WRS2::yuen(df$idade ~ df$genero, tr = 0.2)

# Aplicando o permutation t-test
pacman::p_load(coin) # esse pacote tem algumas funções muito interessantes
coin::oneway_test(df$idade ~ df$genero, distribution = "approximate")

# https://chatgpt.com/c/a85bd99c-d35e-4013-b697-4fc5ad000a9e
```


### Não Parametrico

```{r Teste de hipotese: Mann Whitney / Wilcox | Post Hoc: Hodges Lehmann}
# Mann Whitney
wilcox.test(df$idade ~ df$genero, conf.int = T)

# Wilcox Paired
#wilcox.test(df$idade~df$genero, conf.int = T, paired = T)
```

```{r Testes de homogenidade}
# Teste de Brown-Forsythe
car::leveneTest(df$idade ~ df$genero, center=median) # variação do teste de Levene porém Usando a mediana

# Teste de Fligner-Killeen
fligner.test(df$idade ~ df$genero) # tem alta robustez contra outliers
```


```{r Mann Whitney ajustado com ajuste das permutações de Fisher-Pitman}
# Mann Whitney ajustado com ajuste das permutações de Fisher-Pitman
coin::wilcox_test(df$idade ~ df$genero, conf.int = T)

coin::median_test(df$idade ~ df$genero)
wilcox.test(df$idade ~ df$genero, conf.int = T)
```
# Outros Testes de hipotese com ajuste de permutações de Fisher-Pitman do pacote *coin*

```{r}
df = dff
# Testes de hipotese com ajuste de permutações de Fisher-Pitman
coin::independence_test(df$idade ~ df$genero)
coin::oneway_test(df$idade ~ df$genero)
coin::wilcox_test(df$idade ~ df$genero, conf.int = T)
coin::normal_test(df$idade ~ df$genero)
coin::median_test(df$idade ~ df$genero)
coin::savage_test(df$idade ~ df$genero)$p.value
resultado <- coin::savage_test(df$idade ~ df$genero)
pvalor <- coin::pvalue(resultado)
pvalor

wilcox.test()
```


## Três ou mais Grupos

### Parametricos

```{r Teste de Hipotese: Anova}
aov(var_num ~ tratamentos, data=df) %>% summary()
```

```{r Dunnet}
multcomp::glht(teste_hip, linfct = mcp(tratamentos = "Dunnett")) %>% summary()
```

```{r Tukey}
TukeyHSD(teste_hip)
```

### Não Parametricos

```{r Teste de hipotese: Kruskal Wallis}
kruskal.test(var_num ~ tratamentos, data=df)
```


```{r Dunn}
dunn.test::dunn.test(df$var_num, df$tratamentos, method="bonferroni")
```


```{r Bonferroni}
#qualquer teste
pairwise.t.test(df$var_num, df$tratamentos, p.adjust.method = "bonferroni", data=df)
```

### Pareado

```{r}
box_pareado(df[c('momento_1', 'momento_2', 'momento_3')], 'momento')
```


```{r Preparando os dados}
df_filter = dplyr::select(df, momento_1, momento_2, momento_3)
df_filter = na.omit(df_filter)
df_filter_matrix = as.matrix(df_filter)
df_filter
```

```{r Teste de hipotese: Friedman}
friedman.test(df_filter_matrix)
```

```{r Nemenyi}
PMCMRplus::frdAllPairsNemenyiTest(df_filter_matrix) %>% summary()
```

### Linear Mixed Effect Model

```{r Grafico}
# box_pareado(df[c('momento_1', 'momento_2', 'momento_3', 'tratamentos')], 'momento')
# box_pareado(df[c('momento_1', 'momento_2', 'momento_3', 'tratamentos')], 'momento') + facet_grid(~tratamentos)
```

```{r organizando os dados - formato longo}

df_filter = dplyr::select(df, momento_1, momento_2, momento_3, tratamentos)
df_filter = na.omit(df_filter)

# Transformando para o formato longo
df_filter$ID = 1:nrow(df_filter)
dados_long = pivot_longer(df_filter, cols = starts_with('momento'), 
                           names_to = "momentos", values_to = "medida_numerica")

# Realizando múltiplas comparações para interações
dados_long$inter_ <- factor(interaction(dados_long$tratamentos, dados_long$momentos))
dados_long

```

```{r pacotes}
#library(miscTools) # lmer
library(multcomp) # para avaliar multcomparaçõess

library(lmerTest) # é melhor que library(lme4)
library(MuMIn) # R quadrado para modelos mistos # 
# R2m = proporção explica apenas pelas variaveis fixas 
# R2c = proporção explica pelas variaveis fixas e aleatoria # R quadrado geral
# r.squaredGLMM(modelo) #código de aplicação

library(pander)
# anova(modelo) %>% pander()
# para avaliar a significancia geral dos preditores

```


```{r aplicando modelo: intereção apenas com intercepto}

# primeiro modelo teste 
modelo = lmerTest::lmer(medida_numerica ~ momentos + (1|ID), data= dados_long, REML=F)
statgsa::lm_model_eval(modelo) %>% round(2)
summary(modelo)

# segundo modelo teste
modelo = lmerTest::lmer(medida_numerica ~ momentos * tratamentos + (1|ID), data= dados_long, REML=F)
statgsa::lm_model_eval(modelo) %>% round(2)
summary(modelo)

# terceiro modelo teste # MODELO ESCOLHIDO
modelo = lmerTest::lmer(medida_numerica ~ inter_ + (1|ID), data= dados_long, REML=F)
statgsa::lm_model_eval(modelo) %>% round(2)
summary(modelo)

post_hoc = multcomp::glht(modelo, linfct = mcp(inter_ = "Tukey", interaction_average=TRUE))
post_hoc %>% summary()
post_hoc %>% confint()

```

```{r aplicando modelo: intereção com intercepto e inclinação}

# primeiro modelo teste 
modelo = lmerTest::lmer(medida_numerica ~ momentos + (momentos|ID), data= dados_long, REML=F)
metricas_de_avaliacao_regressao(dados_long, modelo, 'medida_numerica')

# segundo modelo teste
modelo = lmerTest::lmer(medida_numerica ~ momentos * tratamentos + (1|ID), data= dados_long, REML=F)
metricas_de_avaliacao_regressao(dados_long, modelo, 'medida_numerica')
summary(modelo)

# terceiro modelo teste # MODELO ESCOLHIDO
modelo = lmerTest::lmer(medida_numerica ~ inter_ + (1|ID), data= dados_long, REML=F)
metricas_de_avaliacao_regressao(dados_long, modelo, 'medida_numerica')
summary(modelo)

summary(modelo)
post_hoc = multcomp::glht(modelo, linfct = mcp(inter_ = "Tukey", interaction_average=TRUE)) # Post test do modelo
summary(post_hoc)
confint(post_hoc)

```


```{r}
statgsa::summary_num_parametric_groups(df, 'momento_1', 'tratamentos')
df %>% group_by(tratamentos) %>% summarise(media = mean(momento_1))
```

```{r}
box_pareado(df[c('momento_1', 'momento_2', 'momento_3', 'tratamentos')], 'momento') + facet_grid(~tratamentos)
```


# Categorico vs Categorico

https://chat.openai.com/c/fbb1b4e2-f18a-4e98-9282-f09fc0bd2f7f

```{r Teste de Hipotese: Fisher}
teste_hip = fisher.test(df$desfecho, df$tratamentos)
teste_hip
```


```{r Teste de Hipotese: Qui-Quadrado}
teste_hip = chisq.test(df$desfecho, df$tratamentos)
teste_hip
```


```{r Qui-Quadrado e Analise de Residuos}
teste_hip = chisq.test(df$desfecho, df$tratamentos)

# Valores observados
teste_hip$observed

# Valores esperados
teste_hip$expected

# Resíduos
teste_hip$residuals

# Resíduos padronizados
teste_hip$stdres
```


```{r Multiple Comparisons using multcomp in R}
# Ajustar um modelo linear generalizado
glm_model = glm(desfecho ~ tratamentos, family = binomial, data=df)
summary(glm_model)
exp(cbind(OR=coef(glm_model), confint(glm_model))) %>% round(2)
# predict(glm_model, type="response") # predicted values
# residuals(glm_model, type="deviance") # residuals

# Realizar comparações múltiplas
comp = multcomp::glht(glm_model, linfct = mcp(tratamentos = "Tukey"))

# Tabela com Multicomparações - Post Hoc
comp %>% summary()

# Tabela o intervalos de confiança
comp %>% confint()
```


```{r pairwise Nominal Independence with rcompanion}
library(rcompanion)

tabela = table(df$desfecho, df$tratamentos)

# Tabela com Multicomparações - Post Hoc
pos_teste = rcompanion::pairwiseNominalIndependence(tabela, fisher = FALSE,
                                                    gtest  = FALSE, chisq  = TRUE, method = "holm")
pos_teste

# pos_teste = apply_retorne_p(pos_teste, "p.Chisq")
# pos_teste = apply_retorne_p(pos_teste, "p.adj.Chisq")
# pos_teste
```


```{r pairwise.prop.test}
tabela = table(df$tratamentos, df$desfecho)

# Tabela com Multicomparações - Post Hoc
pos_teste = pairwise.prop.test(tabela)
pos_teste
```


```{r Anova}
resultados = aov(as.numeric(desfecho) ~ tratamentos, data=df) 

# Teste de Hipotese
summary(resultados)

# Tabela com Multicomparações - Post Hoc
pos_teste = TukeyHSD(resultados)
pos_teste
```













































```{r}
# l_y = 33
# #traços
# y_altura_ab = 29
# y_altura_bc = 30
# y_altura_ac = 32
# summary(df$var_num)
# texto_altura_ab = y_altura_ab + 1
# texto_altura_bc = y_altura_bc + 1
# texto_altura_ac = y_altura_ac + 1
# 
# subtitulo = paste(valor_p, '(Anova)')
# 
# ggplot(df, aes(x=as.factor(x=tratamentos), y=var_num, fill=as.factor(tratamentos))) + 
#   geom_jitter(alpha=0.5, show.legend = F, size=2.5, position=position_jitter(0.25)) +
#   geom_violin(alpha=0.2, show.legend = F, fill='white') +
#   geom_boxplot(alpha=0.8, show.legend = F, width=0.5) + 
#   geom_errorbar(stat = "summary", fun.data = "mean_se", width= 0.3, color="white") +
#   geom_point(stat = "summary", fun = "mean", show.legend = F, color="red", size=2) +
#   labs(x="Groups", y='Var', subtitle=subtitulo) + 
#   theme(legend.position = "bottom") + theme_bw() +
#   scale_y_continuous(limits = c(10, 33), breaks=seq(from = 10, to = 100, by = 2)) +
#   # COMPARAÇÃO A e B
#   geom_segment(aes(x='A',xend ='B', y=y_altura_ab, yend=y_altura_ab), color = "black") +
#   geom_segment(aes(x='A',xend ='A', y=y_altura_ab, yend=y_altura_ab-.5), color = "black") +
#   geom_segment(aes(x='B',xend ='B', y=y_altura_ab, yend=y_altura_ab-.5), color = "black") +
#   annotate("text", x=1.5, y=texto_altura_ab, label=p_ab, vjust = 0.7, size = 4, color = "black") +
#   # COMPARAÇÃO B e C
#   geom_segment(aes(x='B',xend ='C', y=y_altura_bc, yend=y_altura_bc), color = "black") +
#   geom_segment(aes(x='B',xend ='B', y=y_altura_bc, yend=y_altura_bc-.5), color = "black") +
#   geom_segment(aes(x='C',xend ='C', y=y_altura_bc, yend=y_altura_bc-.5), color = "black") +
#   annotate("text", x=2.5, y=texto_altura_bc, label=p_bc, vjust = 0.7, size = 4, color = "black") +
#   # COMPARAÇÃO A e C
#   geom_segment(aes(x='A',xend ='C', y=y_altura_ac, yend=y_altura_ac), color = "black") +
#   geom_segment(aes(x='A',xend ='A', y=y_altura_ac, yend=y_altura_ac-.5), color = "black") +
#   geom_segment(aes(x='C',xend ='C', y=y_altura_ac, yend=y_altura_ac-.5), color = "black") + 
#   annotate("text", x=2, y=texto_altura_ac, label=p_ac, vjust = 0.7, size = 4, color = "black")
# 
# #ggsave("SAULOO.png", height=15, width=15, units="cm", dpi= 600)
# #######
# 
# y = matrix(c(
#   3.88, 5.64, 5.76, 4.25, 5.91, 4.33, 30.58, 30.14, 16.92,
#   23.19, 26.74, 10.91, 25.24, 33.52, 25.45, 18.85, 20.45,
#   26.67, 4.44, 7.94, 4.04, 4.4, 4.23, 4.36, 29.41, 30.72,
#   32.92, 28.23, 23.35, 12, 38.87, 33.12, 39.15, 28.06, 38.23, 26.65),nrow=6, ncol=6,
# dimnames=list(1:6, LETTERS[1:6]))
# 
# 
# frdAllPairsNemenyiTest(y)
# friedmanTest(y)

```

https://chatgpt.com/share/d27612cd-3eec-4ba8-b385-6b0862bb26de
```{r}
binom.test(15, 100, p = 0.20, alternative = c("less")) #distribuição binomial
prop.test(15, 100, p = 0.20, alternative="less", correct="TRUE") #distrubuição qui-quadrado
prop.test(15, 100, p = 0.20, alternative="less", correct="FALSE") #distribuição normal
```

